// open-studs — bundled SCAD library.
// Generated by scripts/bundle_scad.py — do not edit by hand.
//
// This file concatenates the full OpenSCAD source tree so a single
// downloaded .scad from the configurator renders in OpenSCAD without
// the rest of the repo. To make local changes, edit the source in
// bracelet.scad / core/ / studs/ / latches/ / patterns/ and rerun
// `python3 scripts/bundle_scad.py`.

// ===== core/config.scad =====
// core/config.scad — grouped design configuration helpers.
// MIT licensed. See LICENSE-MIT.
//
// The public `studded_bracelet(...)` API stays flat for hand editing, but the
// assembly uses these grouped configs internally. They mirror the GitHub Pages
// configurator sections: band, surface, latch, and export stage.

OPEN_STUDS_FN = 48;

OPEN_STUDS_DEFAULT_CIRCUMFERENCE = 180;
OPEN_STUDS_DEFAULT_WIDTH         = 22;
OPEN_STUDS_DEFAULT_THICKNESS     = 3;
OPEN_STUDS_DEFAULT_CORNER        = 4;
OPEN_STUDS_LATCH_MARGIN          = 25;

OPEN_STUDS_DEFAULT_STUD          = "pyramid";
OPEN_STUDS_DEFAULT_PATTERN       = "single_row";
OPEN_STUDS_DEFAULT_ROWS          = 1;
OPEN_STUDS_DEFAULT_STUD_SIZE     = 6;
OPEN_STUDS_DEFAULT_TIP_RADIUS    = 0.4;

OPEN_STUDS_DEFAULT_SOCKET_DEPTH  = 1.5;
OPEN_STUDS_DEFAULT_HOLE_DIAMETER = 3;

// --- band config -----------------------------------------------------------

function band_config(
    circumference      = OPEN_STUDS_DEFAULT_CIRCUMFERENCE,
    width              = OPEN_STUDS_DEFAULT_WIDTH,
    thickness          = OPEN_STUDS_DEFAULT_THICKNESS,
    corner             = OPEN_STUDS_DEFAULT_CORNER,
    flex_relief        = "none",
    relief_pitch       = 10,
    relief_width       = 1.2,
    relief_depth       = undef,
    relief_edge_margin = 2,
    relief_margin      = OPEN_STUDS_LATCH_MARGIN
) = [
    circumference,
    width,
    thickness,
    corner,
    flex_relief,
    relief_pitch,
    relief_width,
    relief_depth,
    relief_edge_margin,
    relief_margin
];

function band_cfg_length(c)             = c[0];
function band_cfg_width(c)              = c[1];
function band_cfg_thickness(c)          = c[2];
function band_cfg_corner(c)             = c[3];
function band_cfg_flex_relief(c)        = c[4];
function band_cfg_relief_pitch(c)       = c[5];
function band_cfg_relief_width(c)       = c[6];
function band_cfg_relief_depth(c)       = c[7];
function band_cfg_relief_edge_margin(c) = c[8];
function band_cfg_relief_margin(c)      = c[9];

// --- surface config --------------------------------------------------------

function surface_config(
    mode            = "integral",
    stud_module     = OPEN_STUDS_DEFAULT_STUD,
    stud_pattern    = OPEN_STUDS_DEFAULT_PATTERN,
    stud_rows       = OPEN_STUDS_DEFAULT_ROWS,
    stud_size       = OPEN_STUDS_DEFAULT_STUD_SIZE,
    tip_radius      = OPEN_STUDS_DEFAULT_TIP_RADIUS,
    stud_spacing    = undef,
    socket_depth    = OPEN_STUDS_DEFAULT_SOCKET_DEPTH,
    socket_diameter = undef,
    hole_diameter   = OPEN_STUDS_DEFAULT_HOLE_DIAMETER
) = [
    mode,
    stud_module,
    stud_pattern,
    stud_rows,
    stud_size,
    tip_radius,
    stud_spacing,
    socket_depth,
    socket_diameter,
    hole_diameter
];

function surface_cfg_mode(c)            = c[0];
function surface_cfg_stud_module(c)     = c[1];
function surface_cfg_pattern(c)         = c[2];
function surface_cfg_rows(c)            = c[3];
function surface_cfg_stud_size(c)       = c[4];
function surface_cfg_tip_radius(c)      = c[5];
function surface_cfg_spacing(c)         = c[6];
function surface_cfg_socket_depth(c)    = c[7];
function surface_cfg_socket_diameter(c) = c[8];
function surface_cfg_hole_diameter(c)   = c[9];

// --- latch config ----------------------------------------------------------

function latch_config(
    type      = "buckle",
    clearance = OPEN_STUDS_LATCH_MARGIN
) = [
    type,
    clearance
];

function latch_cfg_type(c)      = c[0];
function latch_cfg_clearance(c) = c[1];

// --- export config ---------------------------------------------------------

function export_config(
    stage       = "print_flat",
    test_length = 70
) = [
    stage,
    test_length
];

function export_cfg_stage(c)       = c[0];
function export_cfg_test_length(c) = c[1];

// ===== patterns/single_row.scad =====
// patterns/single_row.scad — evenly-spaced studs along the centerline.
// MIT licensed.
//
// LEARNING-MODE NOTE: spacing strategy is a UX call. We auto-fit: pick the
// number of studs that fits with at least 25 mm of margin at each end (for
// the latch), spaced evenly. Alternative: fixed mm spacing, accept the
// leftover gap. To switch, set `spacing` explicitly when calling.

LATCH_MARGIN              = 25;  // mm at each end
SINGLE_ROW_DEFAULT_SPACING = 12; // mm — used when auto-fit yields nothing

function _single_row_spacing(band_length, spacing) =
    is_undef(spacing) ?
        // auto-fit: aim for ~12 mm spacing, round to fit cleanly
        (band_length - 2 * LATCH_MARGIN) /
            max(1, floor((band_length - 2 * LATCH_MARGIN) / SINGLE_ROW_DEFAULT_SPACING))
        : spacing;

function _single_row_count(band_length, spacing) =
    floor((band_length - 2 * LATCH_MARGIN) / _single_row_spacing(band_length, spacing)) + 1;

function pattern_single_row(band_length, band_width, rows = 1, spacing = undef) =
    let (
        s = _single_row_spacing(band_length, spacing),
        n = _single_row_count(band_length, spacing),
        y = band_width / 2
    )
    [ for (i = [0 : n - 1]) [LATCH_MARGIN + i * s, y] ];

// ===== patterns/double_row.scad =====
// patterns/double_row.scad — two parallel rows, evenly spaced.
// MIT licensed.

DOUBLE_ROW_DEFAULT_SPACING = 12;
DOUBLE_ROW_INSET = 0.28;  // fraction of band width to inset each row from center

function _double_row_spacing(band_length, spacing) =
    is_undef(spacing) ?
        (band_length - 2 * LATCH_MARGIN) /
            max(1, floor((band_length - 2 * LATCH_MARGIN) / DOUBLE_ROW_DEFAULT_SPACING))
        : spacing;

function _double_row_count(band_length, spacing) =
    floor((band_length - 2 * LATCH_MARGIN) / _double_row_spacing(band_length, spacing)) + 1;

function pattern_double_row(band_length, band_width, rows = 2, spacing = undef) =
    let (
        s = _double_row_spacing(band_length, spacing),
        n = _double_row_count(band_length, spacing),
        y1 = band_width * (0.5 - DOUBLE_ROW_INSET),
        y2 = band_width * (0.5 + DOUBLE_ROW_INSET)
    )
    concat(
        [ for (i = [0 : n - 1]) [LATCH_MARGIN + i * s, y1] ],
        [ for (i = [0 : n - 1]) [LATCH_MARGIN + i * s, y2] ]
    );

// ===== patterns/staggered.scad =====
// patterns/staggered.scad — two rows offset by half a step. The classic
// double-row punk look.
// MIT licensed.

STAGGERED_DEFAULT_SPACING = 12;
STAGGERED_INSET = 0.28;

function _staggered_spacing(band_length, spacing) =
    is_undef(spacing) ?
        (band_length - 2 * LATCH_MARGIN) /
            max(1, floor((band_length - 2 * LATCH_MARGIN) / STAGGERED_DEFAULT_SPACING))
        : spacing;

function _staggered_count(band_length, spacing) =
    floor((band_length - 2 * LATCH_MARGIN) / _staggered_spacing(band_length, spacing)) + 1;

function pattern_staggered(band_length, band_width, rows = 2, spacing = undef) =
    let (
        s  = _staggered_spacing(band_length, spacing),
        n  = _staggered_count(band_length, spacing),
        half = s / 2,
        y1 = band_width * (0.5 - STAGGERED_INSET),
        y2 = band_width * (0.5 + STAGGERED_INSET)
    )
    concat(
        [ for (i = [0 : n - 1]) [LATCH_MARGIN + i * s, y1] ],
        [ for (i = [0 : n - 2]) [LATCH_MARGIN + half + i * s, y2] ]
    );

// ===== patterns/cluster.scad =====
// patterns/cluster.scad — small groups of studs with empty space between.
// MIT licensed.
//
// STUB. Signature locked; cluster topology TBD. Returns an empty list for now
// so the bracelet still compiles when this pattern is selected.

function pattern_cluster(band_length, band_width, rows = 1, spacing = undef) =
    [];  // TODO: design cluster topology

// ===== patterns/gradient_size.scad =====
// patterns/gradient_size.scad — studs that grow/shrink along the band.
// MIT licensed.
//
// STUB. Signature locked; this pattern needs the position list to carry size
// info too (currently it only returns [x, y]). Likely a future-extension to
// allow [x, y, size_scale]. For now returns empty so bracelet still compiles.

function pattern_gradient_size(band_length, band_width, rows = 1, spacing = undef) =
    [];  // TODO: extend signature to carry per-stud size scale

// ===== studs/pyramid.scad =====
// studs/pyramid.scad — classic 4-sided pyramid.
// MIT licensed.
//
// Module contract (see CONTRIBUTING.md):
//   stud_pyramid(size, tip_radius, height)
//   - origin at base center, axis along +Z, base on z=0
//
// LEARNING-MODE NOTE: there are three reasonable ways to build a pyramid in
// OpenSCAD. We use `cylinder($fn=4)` because tip_radius drops in cleanly as
// the top radius. Alternatives if you want to revisit:
//   (a) polyhedron with explicit vertices  — most control, no fillet support
//   (b) hull() over a square base and a point — clean, harder to flatten tip
//   (c) minkowski() of (a) with a small sphere — true fillet, slow render

module stud_pyramid(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size : height;

    // cylinder $fn=4 produces a 4-sided prism. To make the *corners* sit at
    // x=±size/2 and y=±size/2, the base radius must be (size/2)*sqrt(2).
    base_r = (size / 2) * sqrt(2);
    top_r  = tip_radius > 0 ? tip_radius * sqrt(2) : 0;

    rotate([0, 0, 45])
        cylinder(h = h, r1 = base_r, r2 = top_r, $fn = 4);
}

// development render

// ===== studs/flat_pyramid.scad =====
// studs/flat_pyramid.scad — low-profile pyramid for daily wear.
// MIT licensed.
//
// Same geometry as `stud_pyramid` but ~40% of the height — sits closer to
// the band so it doesn't catch on clothing.


module stud_flat_pyramid(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 0.4 : height;
    stud_pyramid(size = size, tip_radius = tip_radius, height = h);
}

// ===== studs/dome.scad =====
// studs/dome.scad — half-sphere stud.
// MIT licensed.

module stud_dome(size = 6, tip_radius = 0.4, height = undef) {
    // `size` is the base diameter; `tip_radius` is unused for a dome
    // (the dome is naturally rounded). `height` defaults to a half-sphere.
    r = size / 2;
    h = is_undef(height) ? r : height;

    intersection() {
        sphere(r = r);
        translate([-r, -r, 0]) cube([size, size, h]);
    }
}

// ===== studs/cone_spike.scad =====
// studs/cone_spike.scad — round-base cone spike.
// MIT licensed.

module stud_cone_spike(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 1.2 : height;
    cylinder(h = h, r1 = size / 2, r2 = max(tip_radius, 0.001));
}

// ===== studs/long_spike.scad =====
// studs/long_spike.scad — the dramatic one.
// MIT licensed.
//
// Tall cone spike. ~2.5x size by default. Set tip_radius = 0 for the full
// "do not approach me at the show" aesthetic, ~0.4 for "I'd like to keep my
// eye."

module stud_long_spike(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 2.5 : height;
    cylinder(h = h, r1 = size / 2, r2 = max(tip_radius, 0.001));
}

// ===== studs/diamond.scad =====
// studs/diamond.scad — bipyramid (two pyramids base-to-base).
// MIT licensed.
//
// The widest cross-section sits halfway up; tip and base are both points
// (or flattened by tip_radius). Reads more "gem" than "punk" — both have
// their moments.

module stud_diamond(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 1.4 : height;
    base_r = (size / 2) * sqrt(2);
    top_r  = tip_radius > 0 ? tip_radius * sqrt(2) : 0;

    rotate([0, 0, 45])
        union() {
            // lower half: point at z=0, widest at z=h/2
            cylinder(h = h / 2, r1 = top_r, r2 = base_r, $fn = 4);
            // upper half: widest at z=h/2, point at z=h
            translate([0, 0, h / 2])
                cylinder(h = h / 2, r1 = base_r, r2 = top_r, $fn = 4);
        }
}

// ===== studs/screw_head.scad =====
// studs/screw_head.scad — flat round disc with a slot. Industrial look.
// MIT licensed.

module stud_screw_head(size = 6, tip_radius = 0.4, height = undef) {
    h         = is_undef(height) ? size * 0.25 : height;
    slot_w    = size * 0.15;
    slot_d    = h * 0.4;
    fillet    = min(tip_radius, h * 0.3);

    difference() {
        // disc with a small chamfered top edge if tip_radius > 0
        if (fillet > 0) {
            minkowski() {
                cylinder(h = h - fillet, r = size / 2 - fillet);
                sphere(r = fillet);
            }
        } else {
            cylinder(h = h, r = size / 2);
        }
        // slot
        translate([-size / 2, -slot_w / 2, h - slot_d])
            cube([size, slot_w, slot_d + 0.1]);
    }
}

// ===== studs/rivet.scad =====
// studs/rivet.scad — rounded button rivet, like a tiny mushroom cap.
// MIT licensed.
//
// Industrial set. Looks like a smashed-flat ball bearing. Low profile,
// reads as "loose hardware" in mass on a band.

module stud_rivet(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 0.4 : height;

    // Body: short cylinder with a domed top. The dome is half a flattened
    // sphere intersected with the cap region so it doesn't peak too high.
    cyl_h = h * 0.6;
    dome_h = h * 0.4;

    union() {
        cylinder(h = cyl_h, r = size / 2);
        translate([0, 0, cyl_h]) {
            intersection() {
                scale([1, 1, dome_h / (size / 2)])
                    sphere(r = size / 2, $fn = 32);
                cylinder(h = dome_h, r = size / 2);
            }
        }
    }
}

// ===== studs/hex_bolt.scad =====
// studs/hex_bolt.scad — hex head, like a real bolt sticking up.
// MIT licensed.
//
// Industrial set. The hex shape is achieved via cylinder($fn=6); tip_radius
// chamfers the top edge.

module stud_hex_bolt(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 0.5 : height;

    // Hex head: cylinder with 6 facets, sized so the flat-to-flat distance
    // equals `size`.
    r = size / sqrt(3);  // outer radius for flat-to-flat = size

    if (tip_radius > 0) {
        // Chamfer the top edge by minkowski-summing the top portion with a
        // small sphere. Keeps the bottom crisp where it meets the band.
        union() {
            cylinder(h = h - tip_radius, r = r, $fn = 6);
            translate([0, 0, h - tip_radius])
                minkowski() {
                    cylinder(h = 0.01, r = r - tip_radius, $fn = 6);
                    sphere(r = tip_radius, $fn = 16);
                }
        }
    } else {
        cylinder(h = h, r = r, $fn = 6);
    }
}

// ===== studs/washer.scad =====
// studs/washer.scad — flat ring with a through-hole.
// MIT licensed.
//
// Industrial set. The "negative space" stud — when massed, reads as a row of
// loose washers riveted to the band. Pairs especially well with multi-color
// prints where the hole exposes a different layer color.

module stud_washer(size = 6, tip_radius = 0.4, height = undef) {
    h        = is_undef(height) ? size * 0.25 : height;
    outer_r  = size / 2;
    inner_r  = size * 0.30;
    fillet   = min(tip_radius, h * 0.4);

    difference() {
        if (fillet > 0) {
            minkowski() {
                cylinder(h = max(h - fillet, 0.01), r = outer_r - fillet);
                sphere(r = fillet, $fn = 16);
            }
        } else {
            cylinder(h = h, r = outer_r);
        }
        // through-hole; small overlap so the boolean is clean
        translate([0, 0, -0.1])
            cylinder(h = h + 0.2, r = inner_r);
    }
}

// ===== studs/star.scad =====
// studs/star.scad — 5-pointed star.
// MIT licensed.
//
// Festival set. Polygon star linear_extruded to a low profile. `tip_radius`
// softens the tips so they don't stab through clothing.

module stud_star(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 0.35 : height;
    outer_r = size / 2;
    // 5-point star: alternating outer/inner radii at 10 angles.
    inner_r = outer_r * 0.42;
    points = [
        for (i = [0 : 9]) let (
            angle = i * 36 - 90,         // start pointing up
            r = (i % 2 == 0) ? outer_r : inner_r
        ) [r * cos(angle), r * sin(angle)]
    ];

    if (tip_radius > 0) {
        // Round the tips by offsetting in and back out.
        linear_extrude(height = h)
            offset(r = tip_radius)
                offset(delta = -tip_radius)
                    polygon(points);
    } else {
        linear_extrude(height = h)
            polygon(points);
    }
}

// ===== studs/heart.scad =====
// studs/heart.scad — geometric heart.
// MIT licensed.
//
// Festival set. Two overlapping circles for the lobes + a downward triangle
// for the point. The kawaii option; pairs with pastel TPU.

module stud_heart(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 0.35 : height;
    // Each circle has radius size/4 and sits at the upper-left / upper-right
    // of the bounding box. The triangle apex is at the bottom center.
    lobe_r = size / 4;
    lobe_y =  size / 4;
    lobe_x =  size / 4;

    linear_extrude(height = h)
        union() {
            translate([-lobe_x, lobe_y]) circle(r = lobe_r);
            translate([ lobe_x, lobe_y]) circle(r = lobe_r);
            polygon([
                [-size / 2 - 0.01, lobe_y],
                [ size / 2 + 0.01, lobe_y],
                [ 0,              -size / 2]
            ]);
        }
}

// ===== studs/lightning.scad =====
// studs/lightning.scad — zigzag bolt.
// MIT licensed.
//
// Festival/cyberpunk set. A flash-of-lightning silhouette extruded low.

module stud_lightning(size = 6, tip_radius = 0.4, height = undef) {
    h = is_undef(height) ? size * 0.35 : height;
    // 6-point polygon making a stylized bolt; coords scaled to fit
    // within [-size/2, size/2] in both axes.
    s = size / 2;
    points = [
        [-0.15 * s,  1.00 * s],
        [ 0.55 * s,  0.10 * s],
        [ 0.05 * s,  0.10 * s],
        [ 0.45 * s, -1.00 * s],
        [-0.35 * s, -0.10 * s],
        [ 0.10 * s, -0.10 * s],
    ];

    if (tip_radius > 0) {
        linear_extrude(height = h)
            offset(r = tip_radius)
                offset(delta = -tip_radius)
                    polygon(points);
    } else {
        linear_extrude(height = h)
            polygon(points);
    }
}

// ===== latches/buckle.scad =====
// latches/buckle.scad — pin-through-hole buckle, leather-bracelet authentic.
// MIT licensed.
//
// One end gets the frame + pin; the other end gets a tongue with a row of
// holes. Caller invokes once at each end with end="left" or end="right".
//
// LEARNING-MODE NOTE: hole count and spacing is a UX call. Defaults below
// give 5 holes at 5 mm spacing => 20 mm of size adjustability. Goth subculture
// tends to want fewer, wider holes; festival use wants more, tighter holes.
// To tune, change BUCKLE_HOLES and BUCKLE_HOLE_SPACING. If you change them,
// also update src/open_studs/params.py to match (drift test will fail
// otherwise once Push 2 lands).

BUCKLE_HOLES         = 5;     // count of adjustment holes
BUCKLE_HOLE_SPACING  = 5;     // mm center-to-center
BUCKLE_HOLE_DIAMETER = 3.5;   // mm — sized to the printed pin
BUCKLE_PIN_DIAMETER  = 3.2;   // mm — slightly under hole for friction
BUCKLE_FRAME_LENGTH  = 12;    // mm — length of the buckle frame
BUCKLE_TONGUE_LENGTH = 35;    // mm — length of the tongue past the band

module latch_buckle(band_width, band_thickness, end = "both") {
    if (end == "left" || end == "both")  buckle_frame(band_width, band_thickness);
    if (end == "right" || end == "both") buckle_tongue(band_width, band_thickness);
}

module buckle_frame(band_width, band_thickness) {
    // a rectangular frame sitting at x=0, extending into -X by BUCKLE_FRAME_LENGTH.
    // pin runs across in Y.
    frame_w = band_width + 4;
    frame_l = BUCKLE_FRAME_LENGTH;
    wall    = 2.5;
    bar_d   = BUCKLE_PIN_DIAMETER;

    translate([-frame_l, -2, 0]) {
        difference() {
            // outer block
            cube([frame_l, frame_w, band_thickness]);
            // inner cutout
            translate([wall, wall, -0.1])
                cube([frame_l - 2 * wall, frame_w - 2 * wall, band_thickness + 0.2]);
        }
        // pin bar across the middle
        translate([frame_l / 2, 0, band_thickness / 2])
            rotate([-90, 0, 0])
                cylinder(h = frame_w, d = bar_d, $fn = 24);
    }
}

module buckle_tongue(band_width, band_thickness) {
    // a tongue at x=0 (right end of band) extending +X by BUCKLE_TONGUE_LENGTH,
    // with BUCKLE_HOLES holes punched through.
    tongue_w = band_width * 0.7;
    tongue_l = BUCKLE_TONGUE_LENGTH;

    difference() {
        translate([0, (band_width - tongue_w) / 2, 0])
            linear_extrude(height = band_thickness)
                offset(r = 3) offset(delta = -3)
                    square([tongue_l, tongue_w]);

        // adjustment holes, centered on the tongue, spaced from the band end
        hole_start = 10;
        for (i = [0 : BUCKLE_HOLES - 1])
            translate([hole_start + i * BUCKLE_HOLE_SPACING, band_width / 2, -0.1])
                cylinder(h = band_thickness + 0.2, d = BUCKLE_HOLE_DIAMETER);
    }
}

// development render — show the frame end on a stub of band so you can see
// how it sits.
*latch_buckle(22, 3, end = "both");

// ===== latches/snap.scad =====
// latches/snap.scad — printed peg-and-socket snap closure.
// MIT licensed.
//
// Convention: end="left" extends in -X from origin; end="right" extends in +X.
// Caller places at x=0 for left and translates to band_length for right.
//
// Both ends have a flat tab extending past the band edge. The LEFT tab has
// a small peg pointing up; the RIGHT tab has a matching socket on its
// underside. When worn, the right tab lays on top of the left tab and the
// peg snaps into the socket.

SNAP_TAB_LENGTH    = 14;   // mm — how far the tab extends past the band
SNAP_PEG_DIAMETER  = 4;    // mm
SNAP_PEG_HEIGHT    = 2.5;  // mm — pegs head sticks above the tab top
SNAP_PEG_HEAD_R    = 2.6;  // mm — flared head, slightly wider than the shaft

module _snap_tab(band_width, band_thickness, direction) {
    // direction = -1 for left (extends -X) or +1 for right (extends +X)
    tab_w = band_width * 0.7;
    x0 = direction == -1 ? -SNAP_TAB_LENGTH : 0;
    translate([x0, (band_width - tab_w) / 2, 0])
        linear_extrude(height = band_thickness)
            offset(r = 3) offset(delta = -3)
                square([SNAP_TAB_LENGTH, tab_w]);
}

module latch_snap(band_width, band_thickness, end = "both") {
    if (end == "left" || end == "both") {
        // tab extends -X
        _snap_tab(band_width, band_thickness, direction = -1);
        // peg pointing up at the tab's tip
        translate([-SNAP_TAB_LENGTH * 0.65, band_width / 2, band_thickness])
            union() {
                cylinder(h = SNAP_PEG_HEIGHT * 0.7, d = SNAP_PEG_DIAMETER);
                translate([0, 0, SNAP_PEG_HEIGHT * 0.7])
                    cylinder(h = SNAP_PEG_HEIGHT * 0.3,
                             r1 = SNAP_PEG_DIAMETER / 2,
                             r2 = SNAP_PEG_HEAD_R);
            }
    }
    if (end == "right" || end == "both") {
        // tab extends +X, with a socket cavity in the underside at the tip
        difference() {
            _snap_tab(band_width, band_thickness, direction = +1);
            // socket: cylindrical cavity sized slightly larger than the peg
            // head, opening downward from z=0 (underside of the tab)
            translate([SNAP_TAB_LENGTH * 0.65, band_width / 2, -0.01])
                cylinder(h = band_thickness * 0.7,
                         d = SNAP_PEG_HEAD_R * 2 + 0.4);
        }
    }
}

// ===== latches/loop_post.scad =====
// latches/loop_post.scad — loop frame on one end, T-post on the other.
// MIT licensed.
//
// Convention: end="left" places a small T-headed post UP from the band's top
// surface at x=0; end="right" places a loop-frame extending +X past the
// band end. When worn, the loop-frame slips over the T-post and the post's
// head captures it.

LOOP_POST_DIAMETER     = 5;     // mm — post shaft diameter
LOOP_POST_HEIGHT       = 7;     // mm — post total height
LOOP_POST_HEAD_R       = 4;     // mm — T-head radius (wider than shaft so the loop is captured)
LOOP_FRAME_LENGTH      = 18;    // mm — frame extends past band end
LOOP_FRAME_INNER_W     = 8;     // mm — inner cutout width (must clear post head)
LOOP_FRAME_INNER_L     = 10;    // mm — inner cutout length
LOOP_FRAME_WALL        = 2.5;   // mm

module latch_loop_post(band_width, band_thickness, end = "both") {
    if (end == "left" || end == "both") {
        // T-headed post centered on the band's top surface near x = 0
        translate([0, band_width / 2, band_thickness]) {
            cylinder(h = LOOP_POST_HEIGHT - 1.2, d = LOOP_POST_DIAMETER);
            translate([0, 0, LOOP_POST_HEIGHT - 1.2])
                cylinder(h = 1.2,
                         r1 = LOOP_POST_DIAMETER / 2,
                         r2 = LOOP_POST_HEAD_R);
        }
    }
    if (end == "right" || end == "both") {
        // Loop frame extending +X past the band end
        frame_w = band_width * 0.8;
        translate([0, (band_width - frame_w) / 2, 0])
            difference() {
                // outer rounded-rect
                linear_extrude(height = band_thickness)
                    offset(r = 3) offset(delta = -3)
                        square([LOOP_FRAME_LENGTH, frame_w]);
                // inner cutout for the loop
                translate([
                    (LOOP_FRAME_LENGTH - LOOP_FRAME_INNER_L) / 2,
                    (frame_w - LOOP_FRAME_INNER_W) / 2,
                    -0.1
                ])
                    linear_extrude(height = band_thickness + 0.2)
                        offset(r = 1.5) offset(delta = -1.5)
                            square([LOOP_FRAME_INNER_L, LOOP_FRAME_INNER_W]);
            }
    }
}

// ===== latches/loop_post_v2.scad =====
// latches/loop_post_v2.scad — lower loop/post toggle with a guided keyhole.
// MIT licensed.
//
// Compared with loop_post.scad, this version lowers the post, moves it inboard,
// and gives the loop a large entry hole plus a narrower capture throat.

LOOP2_POST_INSET    = 8;
LOOP2_SHAFT_D       = 4.6;
LOOP2_HEAD_D        = 8.4;
LOOP2_SHAFT_HEIGHT  = 3.0;
LOOP2_HEAD_HEIGHT   = 1.5;
LOOP2_BASE_D        = 9.0;
LOOP2_TAB_LENGTH    = 34;
LOOP2_TAB_WIDTH_FR  = 0.74;
LOOP2_ENTRY_D       = 9.6;
LOOP2_CAPTURE_D     = 5.6;
LOOP2_THROAT_W      = 5.2;
LOOP2_ENTRY_X       = 23;
LOOP2_CAPTURE_X     = 10.5;
LOOP2_RELIEF_D      = 2.2;

module _loop2_round_rect_2d(length, width, radius) {
    offset(r = radius) offset(delta = -radius)
        square([length, width], center = false);
}

module _loop2_post(band_width, band_thickness) {
    translate([LOOP2_POST_INSET, band_width / 2, band_thickness])
        union() {
            cylinder(h = 0.6, d = LOOP2_BASE_D, $fn = 36);
            cylinder(h = LOOP2_SHAFT_HEIGHT, d = LOOP2_SHAFT_D, $fn = 36);
            translate([0, 0, LOOP2_SHAFT_HEIGHT])
                cylinder(
                    h = LOOP2_HEAD_HEIGHT,
                    r1 = LOOP2_SHAFT_D / 2,
                    r2 = LOOP2_HEAD_D / 2,
                    $fn = 36
                );
        }
}

module _loop2_tab(band_width, band_thickness) {
    tab_w = min(band_width * LOOP2_TAB_WIDTH_FR, band_width - 4);
    y0 = (band_width - tab_w) / 2;
    cy = band_width / 2;

    translate([0, y0, 0])
        difference() {
            linear_extrude(height = band_thickness)
                _loop2_round_rect_2d(LOOP2_TAB_LENGTH, tab_w, 3.2);

            translate([LOOP2_ENTRY_X, cy - y0, -0.1])
                cylinder(h = band_thickness + 0.2, d = LOOP2_ENTRY_D, $fn = 40);

            translate([LOOP2_CAPTURE_X, cy - y0, -0.1])
                cylinder(h = band_thickness + 0.2, d = LOOP2_CAPTURE_D, $fn = 32);

            translate([
                LOOP2_CAPTURE_X,
                cy - y0 - LOOP2_THROAT_W / 2,
                -0.1
            ])
                cube([
                    LOOP2_ENTRY_X - LOOP2_CAPTURE_X,
                    LOOP2_THROAT_W,
                    band_thickness + 0.2
                ]);

            for (side = [-1, 1])
                translate([
                    LOOP2_CAPTURE_X - 3.2,
                    cy - y0 + side * (LOOP2_CAPTURE_D / 2 + 2.5),
                    -0.1
                ])
                    cylinder(h = band_thickness + 0.2, d = LOOP2_RELIEF_D, $fn = 18);
        }
}

module latch_loop_post_v2(band_width, band_thickness, end = "both") {
    if (end == "left" || end == "both")
        _loop2_post(band_width, band_thickness);

    if (end == "right" || end == "both")
        _loop2_tab(band_width, band_thickness);
}

// development render

// ===== latches/mushroom_keyhole.scad =====
// latches/mushroom_keyhole.scad — low-profile mushroom post with a keyhole tab.
// MIT licensed.
//
// Closure idea: push the mushroom head through the large entry hole, then pull
// the tab so the shaft slides into the smaller capture hole. TPU stretch keeps
// the narrow throat from releasing accidentally.

MUSHROOM_POST_INSET    = 8;
MUSHROOM_SHAFT_D       = 4.8;
MUSHROOM_HEAD_D        = 8.2;
MUSHROOM_SHAFT_HEIGHT  = 3.4;
MUSHROOM_HEAD_HEIGHT   = 1.6;
MUSHROOM_BASE_D        = 8.8;
MUSHROOM_TAB_LENGTH    = 36;
MUSHROOM_TAB_WIDTH_FR  = 0.68;
MUSHROOM_ENTRY_D       = 9.4;
MUSHROOM_CAPTURE_D     = 5.4;
MUSHROOM_THROAT_W      = 5.1;
MUSHROOM_ENTRY_X       = 12;
MUSHROOM_CAPTURE_X     = 25;

module _mk_round_rect_2d(length, width, radius) {
    offset(r = radius) offset(delta = -radius)
        square([length, width], center = false);
}

module _mushroom_post(band_width, band_thickness) {
    translate([MUSHROOM_POST_INSET, band_width / 2, band_thickness])
        union() {
            cylinder(h = 0.6, d = MUSHROOM_BASE_D, $fn = 36);
            cylinder(h = MUSHROOM_SHAFT_HEIGHT, d = MUSHROOM_SHAFT_D, $fn = 36);
            translate([0, 0, MUSHROOM_SHAFT_HEIGHT])
                cylinder(
                    h = MUSHROOM_HEAD_HEIGHT,
                    r1 = MUSHROOM_SHAFT_D / 2,
                    r2 = MUSHROOM_HEAD_D / 2,
                    $fn = 36
                );
        }
}

module _mushroom_keyhole_tab(band_width, band_thickness) {
    tab_w = min(band_width * MUSHROOM_TAB_WIDTH_FR, band_width - 4);
    y0 = (band_width - tab_w) / 2;
    cy = band_width / 2;

    translate([0, y0, 0])
        difference() {
            linear_extrude(height = band_thickness)
                _mk_round_rect_2d(MUSHROOM_TAB_LENGTH, tab_w, 3);

            translate([MUSHROOM_ENTRY_X, cy - y0, -0.1])
                cylinder(h = band_thickness + 0.2, d = MUSHROOM_ENTRY_D, $fn = 36);

            translate([MUSHROOM_CAPTURE_X, cy - y0, -0.1])
                cylinder(h = band_thickness + 0.2, d = MUSHROOM_CAPTURE_D, $fn = 36);

            translate([
                min(MUSHROOM_ENTRY_X, MUSHROOM_CAPTURE_X),
                cy - y0 - MUSHROOM_THROAT_W / 2,
                -0.1
            ])
                cube([
                    abs(MUSHROOM_ENTRY_X - MUSHROOM_CAPTURE_X),
                    MUSHROOM_THROAT_W,
                    band_thickness + 0.2
                ]);
        }
}

module latch_mushroom_keyhole(band_width, band_thickness, end = "both") {
    if (end == "left" || end == "both")
        _mushroom_post(band_width, band_thickness);

    if (end == "right" || end == "both")
        _mushroom_keyhole_tab(band_width, band_thickness);
}

// development render

// ===== latches/ladder_strap.scad =====
// latches/ladder_strap.scad — adjustable ladder slots over a low catch.
// MIT licensed.
//
// Closure idea: stretch one of the ladder slots over the low catch block.
// This trades elegance for easy adjustability and fast print-test feedback.

LADDER_CATCH_INSET    = 8;
LADDER_CATCH_L        = 5.0;
LADDER_CATCH_HEIGHT   = 2.4;
LADDER_TAB_LENGTH     = 48;
LADDER_TAB_WIDTH_FR   = 0.58;
LADDER_SLOT_COUNT     = 6;
LADDER_SLOT_START_X   = 9;
LADDER_SLOT_SPACING   = 6.2;
LADDER_SLOT_L         = 3.8;
LADDER_SLOT_W         = 10.8;

module _ladder_round_rect_2d(length, width, radius) {
    offset(r = radius) offset(delta = -radius)
        square([length, width], center = false);
}

module _ladder_catch(band_width, band_thickness) {
    catch_w = min(LADDER_SLOT_W - 1.0, band_width - 6);
    translate([
        LADDER_CATCH_INSET - LADDER_CATCH_L / 2,
        (band_width - catch_w) / 2,
        band_thickness
    ])
        linear_extrude(height = LADDER_CATCH_HEIGHT)
            _ladder_round_rect_2d(LADDER_CATCH_L, catch_w, 1.4);
}

module _ladder_tab(band_width, band_thickness) {
    tab_w = min(band_width * LADDER_TAB_WIDTH_FR, band_width - 5);
    y0 = (band_width - tab_w) / 2;
    slot_w = min(LADDER_SLOT_W, tab_w - 2.2);

    translate([0, y0, 0])
        difference() {
            linear_extrude(height = band_thickness)
                _ladder_round_rect_2d(LADDER_TAB_LENGTH, tab_w, 3);

            for (i = [0 : LADDER_SLOT_COUNT - 1])
                translate([
                    LADDER_SLOT_START_X + i * LADDER_SLOT_SPACING - LADDER_SLOT_L / 2,
                    (tab_w - slot_w) / 2,
                    -0.1
                ])
                    linear_extrude(height = band_thickness + 0.2)
                        _ladder_round_rect_2d(LADDER_SLOT_L, slot_w, 1.2);
        }
}

module latch_ladder_strap(band_width, band_thickness, end = "both") {
    if (end == "left" || end == "both")
        _ladder_catch(band_width, band_thickness);

    if (end == "right" || end == "both")
        _ladder_tab(band_width, band_thickness);
}

// development render

// ===== latches/friction_overlap.scad =====
// latches/friction_overlap.scad — no hardware, ends overlap and TPU-on-TPU grip
// holds.
// MIT licensed.
//
// Adds a small taper at both ends (thinner) so the overlap zone doesn't
// double the wrist's wrap diameter visibly. Adjustable by sliding.

module latch_friction_overlap(band_width, band_thickness) {
    taper_l = 18;  // mm of taper into each end

    // left end taper: shrink to half thickness over taper_l
    translate([0, 0, 0])
        rotate([0, 0, 180])
            linear_extrude(height = band_thickness, scale = [0.6, 1.0])
                square([0.01, band_width], center = false);

    // The above is just a visual hint — the actual taper is handled by the
    // band itself; this module is intentionally minimal because friction
    // overlap requires NO added hardware.
}

// development render

// ===== latches/magnetic.scad =====
// latches/magnetic.scad — small puck on each band end holding a glued-in
// 6 mm × 2 mm neodymium disc magnet.
// MIT licensed.
//
// Convention: end="left" places a puck at origin extending +X into the band
// (centered at MAGNET_POCKET_INSET from x=0); end="right" places a puck
// extending -X from origin (centered at -MAGNET_POCKET_INSET). The caller
// translates the right invocation to band_length so it sits inside the band's
// right end.
//
// Print orientation: pocket opens UP (toward +Z) so the magnet drops in from
// above. The user glues with cyanoacrylate. Polarity is the user's
// responsibility — mark each magnet before gluing because you cannot reverse
// it once cured.

MAGNET_DIAMETER     = 6;     // mm
MAGNET_THICKNESS    = 2;     // mm
MAGNET_TOLERANCE    = 0.3;   // mm of slack so the magnet drops in cleanly
MAGNET_PUCK_R       = 5.5;   // mm — puck around the pocket
MAGNET_PUCK_HEIGHT  = 2.6;   // mm above the band
MAGNET_PUCK_INSET   = 8;     // mm — puck center from the band end

module _magnet_puck(band_thickness) {
    // puck sits ON TOP of the band at z = band_thickness, with a downward-
    // opening cylinder removed for the magnet (opening on the puck's TOP face
    // because the puck sits proud of the band — the pocket can open up
    // without breaching the band).
    difference() {
        translate([0, 0, band_thickness])
            cylinder(h = MAGNET_PUCK_HEIGHT, r = MAGNET_PUCK_R);
        // pocket opens at the top of the puck, sunk down to leave a thin floor
        floor_thickness = max(MAGNET_PUCK_HEIGHT - MAGNET_THICKNESS, 0.4);
        translate([0, 0, band_thickness + floor_thickness])
            cylinder(h = MAGNET_THICKNESS + 0.1,
                     d = MAGNET_DIAMETER + MAGNET_TOLERANCE);
    }
}

module latch_magnetic(band_width, band_thickness, end = "both") {
    if (end == "left" || end == "both") {
        translate([MAGNET_PUCK_INSET, band_width / 2, 0])
            _magnet_puck(band_thickness);
    }
    if (end == "right" || end == "both") {
        translate([-MAGNET_PUCK_INSET, band_width / 2, 0])
            _magnet_puck(band_thickness);
    }
}

// ===== core/band.scad =====
// core/band.scad — bracelet substrate geometry.
// MIT licensed. See LICENSE-MIT.


// --- flat printable substrate ---------------------------------------------

module band_strip(length, width, thickness, corner = OPEN_STUDS_DEFAULT_CORNER) {
    linear_extrude(height = thickness)
        if (corner > 0)
            offset(r = corner) offset(delta = -corner)
                square([length, width], center = false);
        else
            square([length, width], center = false);
}

function band_relief_enabled(mode, thickness) =
    mode == "inside_slots" || mode == "slots" ||
    (mode == "auto" && thickness >= 3.6);

function band_relief_depth(thickness, relief_depth) =
    max(0, min(
        thickness - 0.6,
        is_undef(relief_depth) ? max(0, thickness - 1.2) : relief_depth
    ));

module band_flex_relief_cuts(
    length,
    width,
    thickness,
    relief_pitch       = 10,
    relief_width       = 1.2,
    relief_depth       = undef,
    relief_edge_margin = 2,
    relief_margin      = OPEN_STUDS_LATCH_MARGIN
) {
    depth = band_relief_depth(thickness, relief_depth);
    slot_y = relief_edge_margin;
    slot_width = max(0, width - 2 * relief_edge_margin);

    if (relief_pitch > 0 && relief_width > 0 && depth > 0 && slot_width > 0)
        for (x = [relief_margin : relief_pitch : length - relief_margin])
            translate([x - relief_width / 2, slot_y, -0.05])
                cube([relief_width, slot_width, depth + 0.1], center = false);
}

module bracelet_band(
    length,
    width,
    thickness,
    corner             = OPEN_STUDS_DEFAULT_CORNER,
    flex_relief        = "none",
    relief_pitch       = 10,
    relief_width       = 1.2,
    relief_depth       = undef,
    relief_edge_margin = 2,
    relief_margin      = OPEN_STUDS_LATCH_MARGIN
) {
    difference() {
        band_strip(length, width, thickness, corner);

        if (band_relief_enabled(flex_relief, thickness))
            band_flex_relief_cuts(
                length,
                width,
                thickness,
                relief_pitch,
                relief_width,
                relief_depth,
                relief_edge_margin,
                relief_margin
            );
    }
}

module bracelet_band_from_config(cfg) {
    bracelet_band(
        length             = band_cfg_length(cfg),
        width              = band_cfg_width(cfg),
        thickness          = band_cfg_thickness(cfg),
        corner             = band_cfg_corner(cfg),
        flex_relief        = band_cfg_flex_relief(cfg),
        relief_pitch       = band_cfg_relief_pitch(cfg),
        relief_width       = band_cfg_relief_width(cfg),
        relief_depth       = band_cfg_relief_depth(cfg),
        relief_edge_margin = band_cfg_relief_edge_margin(cfg),
        relief_margin      = band_cfg_relief_margin(cfg)
    );
}

// ===== core/surface.scad =====
// core/surface.scad — top-side design and attachment cutouts.
// MIT licensed. See LICENSE-MIT.




// --- dispatch --------------------------------------------------------------

module place_stud(name, size, tip_radius) {
    if      (name == "pyramid")       stud_pyramid(size, tip_radius);
    else if (name == "dome")          stud_dome(size, tip_radius);
    else if (name == "cone_spike")    stud_cone_spike(size, tip_radius);
    else if (name == "long_spike")    stud_long_spike(size, tip_radius);
    else if (name == "diamond")       stud_diamond(size, tip_radius);
    else if (name == "flat_pyramid")  stud_flat_pyramid(size, tip_radius);
    else if (name == "screw_head")    stud_screw_head(size, tip_radius);
    else if (name == "rivet")         stud_rivet(size, tip_radius);
    else if (name == "hex_bolt")      stud_hex_bolt(size, tip_radius);
    else if (name == "washer")        stud_washer(size, tip_radius);
    else if (name == "star")          stud_star(size, tip_radius);
    else if (name == "heart")         stud_heart(size, tip_radius);
    else if (name == "lightning")     stud_lightning(size, tip_radius);
    else echo(str("WARN: unknown stud_module '", name, "'"));
}

function pattern_positions(name, band_length, band_width, rows, spacing) =
      name == "single_row"    ? pattern_single_row(band_length, band_width, rows, spacing)
    : name == "double_row"    ? pattern_double_row(band_length, band_width, rows, spacing)
    : name == "staggered"     ? pattern_staggered(band_length, band_width, rows, spacing)
    : name == "cluster"       ? pattern_cluster(band_length, band_width, rows, spacing)
    : name == "gradient_size" ? pattern_gradient_size(band_length, band_width, rows, spacing)
    : [];

function surface_positions(cfg, band_length, band_width) =
    pattern_positions(
        surface_cfg_pattern(cfg),
        band_length,
        band_width,
        surface_cfg_rows(cfg),
        surface_cfg_spacing(cfg)
    );

function surface_position_is_clear(p, band_length, latch_clearance) =
    p[0] > latch_clearance && p[0] < band_length - latch_clearance;

function surface_socket_diameter(cfg) =
    is_undef(surface_cfg_socket_diameter(cfg)) ?
        surface_cfg_stud_size(cfg) * 0.5 :
        surface_cfg_socket_diameter(cfg);

// --- positive top design ---------------------------------------------------

module bracelet_surface_from_config(surface_cfg, band_cfg, latch_cfg) {
    mode = surface_cfg_mode(surface_cfg);
    length = band_cfg_length(band_cfg);
    width = band_cfg_width(band_cfg);
    thickness = band_cfg_thickness(band_cfg);
    latch_clearance = latch_cfg_clearance(latch_cfg);
    positions = surface_positions(surface_cfg, length, width);

    if (mode == "integral")
        for (p = positions)
            if (surface_position_is_clear(p, length, latch_clearance))
                translate([p[0], p[1], thickness])
                    place_stud(
                        surface_cfg_stud_module(surface_cfg),
                        surface_cfg_stud_size(surface_cfg),
                        surface_cfg_tip_radius(surface_cfg)
                    );
}

// --- negative attachment features -----------------------------------------

module bracelet_surface_cutouts_from_config(surface_cfg, band_cfg, latch_cfg) {
    mode = surface_cfg_mode(surface_cfg);
    length = band_cfg_length(band_cfg);
    width = band_cfg_width(band_cfg);
    thickness = band_cfg_thickness(band_cfg);
    latch_clearance = latch_cfg_clearance(latch_cfg);
    positions = surface_positions(surface_cfg, length, width);

    if (mode == "modular") {
        socket_depth = min(thickness, surface_cfg_socket_depth(surface_cfg));
        socket_d = surface_socket_diameter(surface_cfg);

        for (p = positions)
            if (surface_position_is_clear(p, length, latch_clearance))
                translate([p[0], p[1], thickness - socket_depth])
                    cylinder(h = socket_depth + 0.1, d = socket_d);
    } else if (mode == "bare_with_holes") {
        for (p = positions)
            if (surface_position_is_clear(p, length, latch_clearance))
                translate([p[0], p[1], -0.1])
                    cylinder(
                        h = thickness + 0.2,
                        d = surface_cfg_hole_diameter(surface_cfg)
                    );
    }
}

// ===== core/latch.scad =====
// core/latch.scad — closure assembly dispatch.
// MIT licensed. See LICENSE-MIT.



// Each latch owns its left/right geometry. The assembly places the left side
// at x=0 and the right side at x=band_length when the latch needs two calls.

module place_latch(name, band_width, band_thickness, band_length) {
    if      (name == "buckle")            _place_two_ended(name, band_width, band_thickness, band_length);
    else if (name == "snap")              _place_two_ended(name, band_width, band_thickness, band_length);
    else if (name == "loop_post")         _place_two_ended(name, band_width, band_thickness, band_length);
    else if (name == "mushroom_keyhole")  _place_two_ended(name, band_width, band_thickness, band_length);
    else if (name == "ladder_strap")      _place_two_ended(name, band_width, band_thickness, band_length);
    else if (name == "loop_post_v2")      _place_two_ended(name, band_width, band_thickness, band_length);
    else if (name == "friction_overlap")  _place_two_ended(name, band_width, band_thickness, band_length);
    else if (name == "magnetic")          _place_two_ended(name, band_width, band_thickness, band_length);
    else if (name == "none") { /* no latch */ }
    else echo(str("WARN: unknown latch '", name, "'"));
}

module _place_two_ended(name, band_width, band_thickness, band_length) {
    if      (name == "buckle") {
        latch_buckle(band_width, band_thickness, end = "left");
        translate([band_length, 0, 0])
            latch_buckle(band_width, band_thickness, end = "right");
    }
    else if (name == "snap") {
        latch_snap(band_width, band_thickness, end = "left");
        translate([band_length, 0, 0])
            latch_snap(band_width, band_thickness, end = "right");
    }
    else if (name == "loop_post") {
        latch_loop_post(band_width, band_thickness, end = "left");
        translate([band_length, 0, 0])
            latch_loop_post(band_width, band_thickness, end = "right");
    }
    else if (name == "mushroom_keyhole") {
        latch_mushroom_keyhole(band_width, band_thickness, end = "left");
        translate([band_length, 0, 0])
            latch_mushroom_keyhole(band_width, band_thickness, end = "right");
    }
    else if (name == "ladder_strap") {
        latch_ladder_strap(band_width, band_thickness, end = "left");
        translate([band_length, 0, 0])
            latch_ladder_strap(band_width, band_thickness, end = "right");
    }
    else if (name == "loop_post_v2") {
        latch_loop_post_v2(band_width, band_thickness, end = "left");
        translate([band_length, 0, 0])
            latch_loop_post_v2(band_width, band_thickness, end = "right");
    }
    else if (name == "friction_overlap") {
        latch_friction_overlap(band_width, band_thickness);
    }
    else if (name == "magnetic") {
        latch_magnetic(band_width, band_thickness, end = "left");
        translate([band_length, 0, 0])
            latch_magnetic(band_width, band_thickness, end = "right");
    }
}

module bracelet_latch_from_config(latch_cfg, band_cfg) {
    place_latch(
        latch_cfg_type(latch_cfg),
        band_cfg_width(band_cfg),
        band_cfg_thickness(band_cfg),
        band_cfg_length(band_cfg)
    );
}

// ===== bracelet.scad =====
// open-studs — parametric studded bracelet, source-of-truth.
// MIT licensed. See LICENSE-MIT.
//
// Top-level entry points:
//   - studded_bracelet(...): flat, hand-editable compatibility API.
//   - bracelet_from_config(...): segmented band/surface/latch/export API.
//
// The bracelet is exported flat for printing. The GitHub Pages viewer can
// bend that same STL around a wrist for preview without changing the print
// orientation.
//
// Quick start:
//
//   use <bracelet.scad>
//   studded_bracelet(
//       circumference = 180, width = 22, thickness = 3,
//       stud_module = "long_spike", stud_pattern = "staggered",
//       stud_rows = 2, latch = "buckle", mode = "integral"
//   );



$fn = OPEN_STUDS_FN;

// Compatibility constant for older user files and pattern discussions.
LATCH_MARGIN = OPEN_STUDS_LATCH_MARGIN;

// --- assembly stages -------------------------------------------------------

module bracelet_from_config(
    band    = band_config(),
    surface = surface_config(),
    latch   = latch_config(),
    export  = export_config()
) {
    stage = export_cfg_stage(export);

    if (stage == "print_flat") {
        _bracelet_print_flat(band, surface, latch);
    } else if (stage == "band_only") {
        bracelet_band_from_config(band);
    } else if (stage == "surface_only") {
        _bracelet_surface_only(band, surface, latch);
    } else if (stage == "latch_only") {
        _bracelet_latch_test(band, latch, export);
    } else {
        echo(str(
            "WARN: unknown export stage '", stage,
            "'; valid: print_flat, band_only, surface_only, latch_only"
        ));
        _bracelet_print_flat(band, surface, latch);
    }
}

module _bracelet_print_flat(band, surface, latch) {
    difference() {
        union() {
            bracelet_band_from_config(band);
            bracelet_surface_from_config(surface, band, latch);
            bracelet_latch_from_config(latch, band);
        }

        bracelet_surface_cutouts_from_config(surface, band, latch);
    }
}

module _bracelet_surface_only(band, surface, latch) {
    difference() {
        union() {
            bracelet_band_from_config(band);
            bracelet_surface_from_config(surface, band, latch);
        }

        bracelet_surface_cutouts_from_config(surface, band, latch);
    }
}

module _bracelet_latch_test(band, latch, export) {
    test_band = band_config(
        circumference      = export_cfg_test_length(export),
        width              = band_cfg_width(band),
        thickness          = band_cfg_thickness(band),
        corner             = band_cfg_corner(band),
        flex_relief        = "none",
        relief_margin      = latch_cfg_clearance(latch)
    );

    union() {
        bracelet_band_from_config(test_band);
        bracelet_latch_from_config(latch, test_band);
    }
}

// --- public compatibility API ---------------------------------------------

module studded_bracelet(
    circumference      = OPEN_STUDS_DEFAULT_CIRCUMFERENCE,
    width              = OPEN_STUDS_DEFAULT_WIDTH,
    thickness          = OPEN_STUDS_DEFAULT_THICKNESS,
    stud_module        = OPEN_STUDS_DEFAULT_STUD,
    stud_pattern       = OPEN_STUDS_DEFAULT_PATTERN,
    stud_rows          = OPEN_STUDS_DEFAULT_ROWS,
    stud_size          = OPEN_STUDS_DEFAULT_STUD_SIZE,
    tip_radius         = OPEN_STUDS_DEFAULT_TIP_RADIUS,
    stud_spacing       = undef,
    latch              = "buckle",
    mode               = "integral",
    flex_relief        = "none",
    relief_pitch       = 10,
    relief_width       = 1.2,
    relief_depth       = undef,
    latch_clearance    = OPEN_STUDS_LATCH_MARGIN,
    stage              = "print_flat",
    test_length        = 70
) {
    band_cfg = band_config(
        circumference = circumference,
        width         = width,
        thickness     = thickness,
        flex_relief   = flex_relief,
        relief_pitch  = relief_pitch,
        relief_width  = relief_width,
        relief_depth  = relief_depth,
        relief_margin = latch_clearance
    );

    surface_cfg = surface_config(
        mode         = mode,
        stud_module  = stud_module,
        stud_pattern = stud_pattern,
        stud_rows    = stud_rows,
        stud_size    = stud_size,
        tip_radius   = tip_radius,
        stud_spacing = stud_spacing
    );

    latch_cfg = latch_config(
        type      = latch,
        clearance = latch_clearance
    );

    export_cfg = export_config(
        stage       = stage,
        test_length = test_length
    );

    bracelet_from_config(
        band    = band_cfg,
        surface = surface_cfg,
        latch   = latch_cfg,
        export  = export_cfg
    );
}

// --- default render --------------------------------------------------------
