#!/usr/bin/env python3
"""Concatenate the OpenSCAD source tree into a single self-contained file.

The configurator's "Download SCAD" prepends this bundle to the user's config
so the downloaded file renders in OpenSCAD without the rest of the repo.

Rules per file:
  - Strip `include <...>` and `use <...>` directives (everything is now inline).
  - Strip top-level dev/render calls. These always live AFTER the last `}` in
    the file (the close of the last module's body). Lines after the last `}`
    that aren't blank/comments are dropped.
  - Files without any `{}` (pattern/config files of pure constants and
    functions) are kept as-is.

Run from the repo root:
    python3 scripts/bundle_scad.py
"""

from __future__ import annotations

from pathlib import Path


# Dependency-aware concatenation order. Constants first, then leaves
# (patterns/studs/latches), then core dispatchers, then the top-level
# bracelet.scad. The relative order within a leaf tier doesn't matter.
BUNDLE_ORDER = [
    "core/config.scad",
    "patterns/single_row.scad",
    "patterns/double_row.scad",
    "patterns/staggered.scad",
    "patterns/cluster.scad",
    "patterns/gradient_size.scad",
    "studs/pyramid.scad",
    "studs/flat_pyramid.scad",
    "studs/dome.scad",
    "studs/cone_spike.scad",
    "studs/long_spike.scad",
    "studs/diamond.scad",
    "studs/screw_head.scad",
    "studs/rivet.scad",
    "studs/hex_bolt.scad",
    "studs/washer.scad",
    "studs/star.scad",
    "studs/heart.scad",
    "studs/lightning.scad",
    "latches/buckle.scad",
    "latches/snap.scad",
    "latches/loop_post.scad",
    "latches/loop_post_v2.scad",
    "latches/mushroom_keyhole.scad",
    "latches/ladder_strap.scad",
    "latches/friction_overlap.scad",
    "latches/magnetic.scad",
    "core/band.scad",
    "core/surface.scad",
    "core/latch.scad",
    "bracelet.scad",
]

OUTPUT = "docs/configurator/bracelet_bundled.scad"


def clean_file(text: str) -> str:
    """Strip include/use directives and post-last-`}` dev calls."""
    kept_lines: list[str] = []
    for line in text.split("\n"):
        stripped = line.lstrip()
        if stripped.startswith(("include ", "include<", "use ", "use<")):
            continue
        kept_lines.append(line)
    cleaned = "\n".join(kept_lines)

    last_brace = cleaned.rfind("}")
    if last_brace == -1:
        # No modules in this file — nothing to strip after.
        return cleaned.rstrip() + "\n"

    head = cleaned[: last_brace + 1]
    tail = cleaned[last_brace + 1 :]

    # In the tail, keep only blank lines and comments. Dev-render calls always
    # live here and are the only top-level statements we want to drop.
    tail_kept: list[str] = []
    for line in tail.split("\n"):
        stripped = line.strip()
        if not stripped or stripped.startswith(("//", "/*", "*")):
            tail_kept.append(line)
        # Else: top-level call — drop.

    return (head + "\n".join(tail_kept)).rstrip() + "\n"


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    out_path = root / OUTPUT

    sections: list[str] = []
    sections.append(
        "// open-studs — bundled SCAD library.\n"
        "// Generated by scripts/bundle_scad.py — do not edit by hand.\n"
        "//\n"
        "// This file concatenates the full OpenSCAD source tree so a single\n"
        "// downloaded .scad from the configurator renders in OpenSCAD without\n"
        "// the rest of the repo. To make local changes, edit the source in\n"
        "// bracelet.scad / core/ / studs/ / latches/ / patterns/ and rerun\n"
        "// `python3 scripts/bundle_scad.py`.\n"
    )

    for rel in BUNDLE_ORDER:
        src = root / rel
        if not src.exists():
            raise SystemExit(f"missing source: {src}")
        sections.append(f"// ===== {rel} =====\n{clean_file(src.read_text())}")

    bundled = "\n".join(sections)
    bundled = dedupe_constant_assignments(bundled)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(bundled)
    line_count = bundled.count("\n")
    print(f"wrote {out_path.relative_to(root)} ({line_count} lines)")


def dedupe_constant_assignments(text: str) -> str:
    """Strip duplicate top-level `NAME = value;` lines with identical RHS.

    Files like patterns/{single_row,double_row,staggered}.scad each declare
    `LATCH_MARGIN = 25;` because they were designed to be `use`d (not
    `include`d) and therefore couldn't share the constant. Once bundled into
    one file they all live in the same scope and OpenSCAD warns about the
    redefinition. Drop later occurrences when the value matches the first.
    """
    import re

    seen: dict[str, str] = {}
    pattern = re.compile(r"^([A-Z_][A-Z_0-9]*)\s*=\s*([^;]+);")
    out: list[str] = []
    for line in text.split("\n"):
        m = pattern.match(line.strip())
        if m is None:
            out.append(line)
            continue
        name, value = m.group(1), m.group(2).strip()
        first = seen.get(name)
        if first is None:
            seen[name] = value
            out.append(line)
        elif first == value:
            # Identical redefinition — drop it.
            continue
        else:
            # Different value: keep so behavior is preserved; the human reading
            # the warning will know to investigate.
            out.append(line)
    return "\n".join(out)


if __name__ == "__main__":
    main()
